acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to="user/%y/%m")
    comment = models.TextField()
    age = models.IntegerField(default=1)
    
    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/user/noimage.png"

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 50:
            return f"{self.content[:50]} ..."
        return self.content

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.contrib.auth.hashers import check_password

def delete(req):
    pwck = req.POST.get("pwck")
    if check_password(pwck, req.user.password):
        req.user.pic.delete()
        req.user.delete()
        return redirect("acc:index")
    else:
        # 메세지 출력
        return redirect("acc:profile")

def update(req):
    if req.method == "POST":
        u = req.user
        ue = req.POST.get("umail")
        up = req.POST.get("upass")
        ua = req.POST.get("uage")
        pi = req.FILES.get("upic")
        uc = req.POST.get("ucom")
        if up:
            u.set_password(up)
        u.email = ue
        u.age = ua
        if pi:
            u.pic.delete()
            u.pic = pi
        u.comment = uc
        u.save()
        login(req, u)
        return redirect("acc:profile")
        
    return render(req, "acc/update.html")

def profile(req):
    return render(req, "acc/profile.html")

def signup(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")
        ua = req.POST.get("uage")
        pi = req.FILES.get("upic")
        uc = req.POST.get("ucom")
        try:
            User.objects.create_user(username=un, password=up, age=ua, pic=pi, comment=uc)
            return redirect("acc:login")
        except:
            pass # 메시지 넣을곳!
    return render(req, "acc/signup.html")

def logout_user(req):
    logout(req)
    return redirect("acc:login")

def index(req):
    return render(req, "acc/index.html")

def login_user(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u:
            login(req, u)
            return redirect("acc:index")
        else:
            pass # 메세지할것!!
    return render(req, "acc/login.html")

board/views.py
from django.shortcuts import render,redirect
from .models import Board
from django.utils import timezone
# Create your views here.
def update(req, bpk):
    b = Board.objects.get(id=bpk)

    if req.user != b.writer:
        pass # 경고!!
        return redirect("board:index")

    if req.method == "POST":
        s = req.POST.get("sub")
        c = req.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:detail", bpk)
    context = {
        "b": b
    }
    return render(req, "board/update.html", context)

def create(req):
    if req.method == "POST":
        s = req.POST.get("sub")
        c = req.POST.get("con")
        t = timezone.now()
        Board(subject=s, writer=req.user, content=c, pubdate=t).save()
        return redirect("board:index")
    return render(req, "board/create.html")


def delete(req, bpk):
    b = Board.objects.get(id=bpk)
    if req.user == b.writer:
        b.delete()
    else:
        pass #메세지 넣을곳!!

    return redirect("board:index")

def detail(req, bpk):
    b = Board.objects.get(id=bpk)
    context = {
        "b" : b
    }
    return render(req, "board/detail.html", context)

def index(req):
    b = Board.objects.all()
    context = {
        "bset": b
    }
    return render(req, "board/index.html", context)

templates/acc/index.html
{% extends 'base.html' %}
{% block con %}

    <h1>WELCOME {{ user }} !! 🎉</h1>


{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block con %}
    <h1>LOGIN PAGE</h1>
    
    <form method="post">
        {% csrf_token %}
        <input type="text" name="uname"><br><br>
        <input type="password" name="upass"><br><br>
        <button>로그인</button>
    </form>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}

{% block con %}

    <h1>{{ user }}'s PROFILE</h1>

    <img src="{{ user.getpic }}" width="350px">
    <br><br>
    <table>
        <tr>
            <th>USERNAME</th>
            <td><input type="text" value="{{ user }}" disabled></td>
        </tr>
        <tr>
            <th>AGE</th>
            <td><input type="number" value="{{ user.age }}" disabled></td>
        </tr>
        <tr>
            <th>EMAIL</th>
            <td><input type="text" value="{{ user.email }}" disabled></td>
        </tr>
        <tr>
            <th>COMMENT</th>
            <td><textarea cols="50" rows="5" disabled>{{ user.comment }}</textarea></td>
        </tr>
    </table>
    <br>

    <a href="{% url 'acc:update' %}"><button>정보수정</button></a>
    <button type="button" id="delbutton" onclick="make_del()">계정삭제</button>

    <form method="POST" id="here" action="{% url 'acc:delete' %}">
        {% csrf_token %}
    </form>

    <script>
        function make_del(){
            d = document.getElementById("here");
            bu = document.getElementById("delbutton");
            bu.setAttribute("disabled", "true");
            fo = document.createElement("div");
            fo.innerHTML = "<br><h4><b>삭제하시려면 패스워드를 입력해주세요</b></h4><hr><b>PASSWORD CHECK</b> <input type='password' name='pwck'> <button>삭제</button><br><hr>";
            d.appendChild(fo);
        }
    </script>
    
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}

    <h1>SIGNUP PAGE</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <th>USERNAME</th>
                <td><input type="text" name="uname"></td>
            </tr>
            <tr>
                <th>PASSWORD</th>
                <td><input type="password" name="upass"></td>
            </tr>
            <tr>
                <th>AGE</th>
                <td><input type="number" name="uage"></td>
            </tr>
            <tr>
                <th>PIC</th>
                <td><input type="file" name="upic"></td>
            </tr>
            <tr>
                <th>COMMENT</th>
                <td><textarea cols="50" rows="5" name="ucom"></textarea></td>
            </tr>
        </table>
        <button>가입</button>
    </form>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}

    <h1>{{user}}'s UPDATE PAGE</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <th>PASSWORD</th>
                <td><input type="password" name="upass"></td>
            </tr>
            <tr>
                <th>EMAIL</th>
                <td><input type="text" name="umail" value="{{user.email}}"></td>
            </tr>
            <tr>
                <th>AGE</th>
                <td><input type="number" value="{{ user.age }}" name="uage"></td>
            </tr>
            <tr>
                <th>PIC</th>
                <td><input type="file" name="upic"></td>
            </tr>
            <tr>
                <th>COMMENT</th>
                <td><textarea cols="50" rows="5" name="ucom">{{ user.comment }}</textarea></td>
            </tr>
        </table>
        <button>수정완료</button>
    </form>
{% endblock %}

templates/base.html
<hr>
{% if user.is_authenticated %}
    <div>
        <a href="{% url 'acc:index' %}" class="menu">HOME</a>
        <a href="{% url 'board:index' %}" class="menu">BOARD</a>
        <a href="{% url 'acc:profile' %}" class="menu">PROFILE</a>
        <a href="{% url 'acc:logout' %}" class="menu">LOGOUT</a>
        접속중인 계정 : {{user}}
    </div>
{% else %}
    <div>
        <a href="{% url 'acc:index' %}" class="menu">HOME</a>
        <a href="{% url 'acc:login' %}" class="menu">LOGIN</a>
        <a href="{% url 'acc:signup' %}" class="menu">SIGNUP</a>
    </div>
{% endif %}

<hr>

{% block con %}
{% endblock %}

<style>
    .menu{
        text-decoration: none;
        font-size: 25px;
        color:black;
        font-weight: bold;
        margin-right: 30px;
    }
    .menu:hover{
        color:blue;
    }
</style>

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <br>
    <h1><b>게시글 작성 페이지</b></h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" placeholder="제목을 입력하세요" name="sub"><br><br>
        <textarea cols="80" name="con" rows="8" placeholder="내용을 입력하세요"></textarea><br><br>
        <button>글작성</button>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}

<h1><b>{{ b.subject }}</b></h1>


<img src="{{ b.writer.getpic }}" width="200px">
<div>
    written by <b>{{b.writer}}</b>
</div>
<br>
<textarea cols="80" rows="8" disabled>{{ b.content }}</textarea>
<br><br>
<a href="{% url 'board:index' %}"><button>목록</button></a>
{% if user == b.writer %}
    <a href="{% url 'board:update' b.id %}"><button>수정</button></a>
    <a href="{% url 'board:delete' b.id %}"><button>삭제</button></a>
{% endif %}
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}
    
    <br><br>
    <h1>BOARD PAGE</h1>

    <a href="{% url 'board:create' %}"><button>글작성</button></a>
    <br><br>

    <table border="1">
        <tr>
            <th>NO</th>
            <th>SUBJECT</th>
            <th>SUMMARY</th>
            <th>WRITER</th>
            <th>LIKEY</th>
        </tr>
        {% if bset %}
            {% for i in bset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                    <td>{{ i.summary }}</td>
                    <td>{{ i.writer }}</td>
                    <td>0</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <th colspan="5">첫번째 게시글을 작성해주세요 🤣</th>
            </tr>
        {% endif %}
    </table>

{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <br>
    <h1><b>{{ b.subject }} 수정 페이지</b></h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" placeholder="제목을 입력하세요" name="sub" value="{{ b.subject }}"><br><br>
        <textarea cols="80" name="con" rows="8" placeholder="내용을 입력하세요">{{ b.content }}</textarea><br><br>
        <button>수정완료</button>
    </form>
{% endblock %}